version: 0.0
os: linux
files:
  - source: ./wordsCombo-1.0-SNAPSHOT.jar
    destination: /tmp
  - source: ./start.sh
    destination: /tmp

permissions:
  - object: /tmp
    pattern: "*.sh"
    owner: ec2-user
    mode: 555

hooks:
  ApplicationStart:
    - location: /tmp/start.sh

