version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Java package...
      - mvn package
      - echo Building Docker image...
      - docker build -t wordscombo .
      - docker tag wordscombo:latest 615667466743.dkr.ecr.eu-west-1.amazonaws.com/wordscombo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 615667466743.dkr.ecr.eu-west-1.amazonaws.com/wordscombo:latest
      - echo Creating imagedefinitions.json
      - printf '[{"name":"wordscombo","imageUri":"615667466743.dkr.ecr.eu-west-1.amazonaws.com/wordscombo:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - Dockerrun.aws.json
    - imagedefinitions.json